# Generated by Django 3.1.6 on 2021-02-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('balance', models.TextField()),
                ('last_in', models.TextField()),
                ('last_out', models.TextField()),
                ('number_of_ins', models.TextField()),
                ('number_of_outs', models.TextField()),
            ],
        ),
    ]
