# Generated by Django 3.1.6 on 2021-02-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='misc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='last_in',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='last_out',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='number_of_ins',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='number_of_outs',
            field=models.TextField(blank=True),
        ),
    ]
