# Generated by Django 3.1.6 on 2021-02-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0004_auto_20210214_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='number_of_ins',
            new_name='in_nums',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='number_of_outs',
            new_name='out_nums',
        ),
    ]
