# Generated by Django 3.1.6 on 2021-02-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0005_auto_20210216_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='category',
            field=models.TextField(default='normal'),
        ),
    ]
