# Generated by Django 3.1.6 on 2021-02-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0006_wallet_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='transactions_delta',
            field=models.TextField(default='[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]'),
        ),
    ]
