# Generated by Django 3.1.6 on 2021-02-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0008_auto_20210223_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregator',
            name='total_wallets',
            field=models.TextField(blank=True),
        ),
    ]
