# Generated by Django 3.1.6 on 2021-02-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0009_aggregator_total_wallets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aggregator',
            old_name='total_wallets',
            new_name='new_wallets',
        ),
    ]
