# Generated by Django 3.1.6 on 2021-02-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0010_auto_20210223_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='in_nums',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='out_nums',
            field=models.TextField(default='0'),
        ),
    ]
