# Generated by Django 3.1.6 on 2021-02-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0013_auto_20210223_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregator',
            name='transactions_delta_all',
            field=models.TextField(default='0'),
        ),
    ]
