# Generated by Django 3.1.6 on 2021-02-24 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0014_aggregator_transactions_delta_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('marked_balance', models.TextField(default='0')),
                ('marked_delta', models.TextField(default='0')),
                ('marked_delta_per', models.TextField(default='0')),
                ('exchanges_balance', models.TextField(default='0')),
                ('exchanges_delta', models.TextField(default='0')),
                ('exchanges_delta_per', models.TextField(default='0')),
                ('algo_balance', models.TextField(default='0')),
                ('algo_delta', models.TextField(default='0')),
                ('algo_delta_per', models.TextField(default='0')),
                ('trading_balance', models.TextField(default='0')),
                ('trading_delta', models.TextField(default='0')),
                ('trading_delta_per', models.TextField(default='0')),
            ],
        ),
    ]
