# Generated by Django 3.1.6 on 2021-02-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0015_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregator',
            name='delta_per',
            field=models.TextField(default='0'),
        ),
    ]
