# Generated by Django 3.1.6 on 2021-03-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0016_aggregator_delta_per'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregator',
            name='real_delta',
            field=models.TextField(default='0'),
        ),
    ]
