# Generated by Django 3.1.6 on 2021-03-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0017_aggregator_real_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregator',
            name='btc_price',
            field=models.TextField(default='0'),
        ),
    ]
