# Generated by Django 3.1.6 on 2021-03-06 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0018_aggregator_btc_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='reading_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
