# Generated by Django 3.1.6 on 2021-03-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0020_wallet_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='reading_date',
            new_name='first_reading_date',
        ),
    ]
