# Generated by Django 3.1.6 on 2021-03-13 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0021_auto_20210312_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('wallet_list', models.TextField(blank=True)),
            ],
        ),
    ]
